# Generated by Django 5.0.4 on 2024-06-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='blog',
            new_name='post',
        ),
    ]
